FROM node:16

WORKDIR /app

COPY server/package*.json ./

RUN npm install

# Install pg and @types/pg (if not already installed)
RUN npm install pg @node-rs/bcrypt && npm install --save-dev @types/pg

COPY server .

EXPOSE 3000

CMD ["npm", "start"]